### ISSUE TITLE
Failed to get image from provider

### ISSUE THREAD

**Issue by xiangzhai** [giucam/orbital#15]
[orbital-client warning] file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/preferences-desktop

Do I need to install some theme and icon?

**Comment by giucam** [comment]
By default it looks for the oxygen theme, i haven't looked yet into making it fallback to another one. If you don't have it you must currently change the hardcoded default here (https://github.com/giucam/orbital/blob/master/src/client/shellui.cpp#L46). Once you have a configuration file you'll be able to change the theme by editing that.

**Comment by xiangzhai** [comment]
Huh, thank @giucam I have not installed any DE yet (openbox && qtpanel) ;P I will install oxygen-icons(-svg)

**Comment by giucam** [comment]
You don't need the svg ones, they'll not be used.

**Comment by xiangzhai** [comment]
![Image of orbital-launch](http://ww1.sinaimg.cn/large/658b3ba1jw1eoh8wi2qhuj22gw1uonpe.jpg)

Is there screenshooter key binding?

**Comment by giucam** [comment]
> Is there screenshooter key binding?

Yes, win key+print screen.

**Comment by xiangzhai** [comment]
Thanks ;P

**Comment by gld1982ltd** [comment]
I'm getting the same kind of errors.

![orbital_on_x_screenshot_2015-02-02_12-28-26](https://cloud.githubusercontent.com/assets/2688954/6006309/18b2c5fc-aad7-11e4-9bd3-f04ad75a8fdc.png)

**Comment by giucam** [comment]
I recently discovered http://qt-apps.org/content/show.php?action=content&content=168066
I suggest you use that to set an icon theme, and then export QT_QPA_PLATFORMTHEME=qt5ct.

**Comment by gld1982ltd** [comment]
That fixes the image problems. Thanks!
