### ISSUE TITLE
orbital-launcher is unvisible?

### ISSUE THREAD

**Issue by xiangzhai** [giucam/orbital#17]
Hi @giucam 

![orbital-snapshot6](https://cloud.githubusercontent.com/assets/851100/5852659/55e13f10-a255-11e4-8de8-cbd340d9307a.png)

I simply read orbital/src/launcher source code, orbital-launcher is app-launcher, right? list ALL apps, and run (clicked) it? but why it is unvisible? 

Regards,
Leslie Zhai

**Comment by giucam** [comment]
After you start it you show it with win key+f2. I make it start automatically but having an autostart dekstop file for it.

**Comment by xiangzhai** [comment]
LOL it worked ;P

![orbital-snapshot7](https://cloud.githubusercontent.com/assets/851100/5853296/4bab0db6-a25d-11e4-9b51-c2c7ec37650d.png)
