### ISSUE TITLE
client.cpp compile error - missing header file

### ISSUE THREAD

**Issue by ThoriumEnergy** [giucam/orbital#26]
during make
client.cpp:37:43: fatal error
qpa/qplatformnativeinterface.h: No such file or directory
#include <qpa/qplatformnativeinterface.h>

**Comment by giucam** [comment]
Mmh. What does a 'sudo find / -name qplatformnativeinterface.h' return?

**Comment by ThoriumEnergy** [comment]
Not found.  If I do 'sudo find / -name qplatform*  '  I start to find files, but I see now what you are hinting at.  If I do qmake -v, I get
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/x86_64-linux-gnu
So, I see now I need a later version of Qt.  I will install and retry the orbital make. - Thanks

**Comment by giucam** [comment]
Actually no, 5.3.2 should have it. I think you have some problems in your setup.
