### ISSUE TITLE
 Backends not found in CMake

### ISSUE THREAD

**Issue by FireFaced** [giucam/orbital#27]
This is annoying, CMake is throwing this error:
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
wdrm
    linked by target "drm-backend" in directory /home/firefaced/builds/orbital/src/compositor/drm-backend
wwl
    linked by target "wayland-backend" in directory /home/firefaced/builds/orbital/src/compositor/wayland-backend
wx11
    linked by target "x11-backend" in directory /home/firefaced/builds/orbital/src/compositor/x11-backend

-- Configuring incomplete, errors occurred!
See also "/home/firefaced/builds/orbital/build/CMakeFiles/CMakeOutput.log".

Can you help me out with this? I'm on Arch

**Comment by giucam** [comment]
Did you build weston from the libweston branch here? https://github.com/giucam/weston

**Comment by FireFaced** [comment]
I got weston from pacman

**Comment by giucam** [comment]
So that's the problem.
