### ISSUE TITLE
Plasma launched on top of orbital workspace

### ISSUE THREAD

**Issue by Svadkos** [giucam/orbital#36]
https://imgur.com/a/tFE0T

**Comment by giucam** [comment]
I suppose you have an autostart file for plasma. Look at the orbital output, it will tell you which autostart files it is running. You will need to redirect the output to a file if you are starting it in a tty: "orbital > out 2>&1"

Unrelated, but i'm also noticing you're missing the icons, i suggest you use qt5ct to tell orbital which icon theme to use.

**Comment by Svadkos** [comment]
Orbital takes it from /etc/xdg/autostart, even with 'OnlyShowIn=KDE' variable in desktop entery. I think it not supposed to do so.
```
autostart!!
populate /home/vigi/.config/autostart
populate /etc/xdg/autostart

Autostarting /etc/xdg/autostart/at-spi-dbus-bus.desktop: '/usr/lib/at-spi2-core/at-spi-bus-launcher --launch-immediately'
Autostarting /etc/xdg/autostart/baloo_file.desktop: 'baloo_file'
Autostarting /etc/xdg/autostart/kdeconnectd.desktop: 'lib/kdeconnectd'
Autostarting /etc/xdg/autostart/krunner.desktop: 'krunner'
Autostarting /etc/xdg/autostart/nm-applet.desktop: 'nm-applet'
Autostarting /etc/xdg/autostart/orbital-launcher.desktop: 'orbital-launcher'
Autostarting /etc/xdg/autostart/org.kde.klipper.desktop: 'klipper'
Autostarting /etc/xdg/autostart/plasmashell.desktop: 'plasmashell --shut-up'
Autostarting /etc/xdg/autostart/polkit-kde-authentication-agent-1.desktop: '/usr/lib/polkit-kde/polkit-kde-authentication-agent-1'
Autostarting /etc/xdg/autostart/pulseaudio.desktop: 'start-pulseaudio-x11'
Autostarting /etc/xdg/autostart/xembedsniproxy.desktop: 'xembedsniproxy'
```
> Unrelated, but i'm also noticing you're missing the icons, i suggest you use qt5ct to tell orbital which icon theme to use.

You mean missing weston-terminal icon? I just not installed it.
Or maybe there something else, don't know, i use i3 now, so not see any icons, maybe i broke some theme and didn't notice that.
There a lot of errors on this:
```
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/preferences-desktop
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/document-revert
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/preferences-desktop-wallpaper
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/go-up
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/user-home
[D orbital-client - /tmp/makepkg/orbital-git/src/orbital/src/client/element.cpp:421] == Creating "background" in 387 ms.
[W orbital-client - file:///usr/share/orbital/elements/background/Background.qml:162] == file:///usr/share/orbital/elements/background/Background.qml:162:9: QML Image: Cannot open: file:///usr/local/share/weston/pattern.png
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/transform-move
[D orbital-client - /tmp/makepkg/orbital-git/src/orbital/src/client/element.cpp:421] == Creating "panel" in 11 ms.
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/image-missing
[D orbital-client - /tmp/makepkg/orbital-git/src/orbital/src/client/element.cpp:421] == Creating "launcher" in 58 ms.
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/utilities-terminal
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/preferences-other
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/edit-delete
[D orbital-client - /tmp/makepkg/orbital-git/src/orbital/src/client/element.cpp:421] == Creating "pager" in 5 ms.
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/preferences-other
[W orbital-client - file::/qml/Icon.qml:42] == file::/qml/Icon.qml:42:9: QML Image: Failed to get image from provider: image://icon/edit-delete
```
And so on.

Also, one more thing: i can't see other tty's (it is covered with stripes), and sometimes if i moved cursor to some window that use xwayland, Firefox for example, tty becomes normal, but not always. Don't know even how to test it. Create new issue?

**Comment by giucam** [comment]
> Or maybe there something else, don't know, i use i3 now, so not see any icons, maybe i broke some theme and didn't notice that.
There a lot of errors on this:

Yes, those errors mean you're missing icons. I'm not sure what you mean you're using i3...

> Also, one more thing: i can't see other tty's (it is covered with stripes), and sometimes if i moved cursor to some window that use xwayland, Firefox for example, tty becomes normal, but not always. Don't know even how to test it. Create new issue?

You mean when you switch to another tty they have stripes? That's odd, can you try with weston?

**Comment by Svadkos** [comment]
> Yes, those errors mean you're missing icons. I'm not sure what you mean you're using i3...

I mean, i'm use here not so much gui apps, and seems that problems only in qt5 soft and i could just miss that.
Also, here solution https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE

>You mean when you switch to another tty they have stripes? 

Yes, horizontal stripes in center and bottom of screen, and input still works.
With weston i can switch to another tty with no problems.
Also always works in that sequence:
1. start orbital
2. switch to another wm (It does not matter Wayland or X)
3. switch to tty

And i noticed that cursor from orbital or weston stays in another wayland wm - sway. But i don't know whose problem it is.

**Comment by giucam** [comment]
> I mean, i'm use here not so much gui apps, and seems that problems only in qt5 soft and i could just miss that.
Also, here solution https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE

Right, the wiki is right and i highly suggest you fix that because they are important in orbital.


Regarding the tty problem, i am out of ideas... do you run weston with weston-launch or just weston?
Anyway, please open a new issue for that.

**Comment by Svadkos** [comment]
> do you run weston with weston-launch or just weston?

I tried both and it doesn't matter.
