### ISSUE TITLE
Black wallpaper and empty icons

### ISSUE THREAD

**Issue by Kais-DkM** [giucam/orbital#41]
I downloaded package on arch linux by AUR, and executed on tty, but nothing appears except black screen.
[http://imgur.com/K5FZAZ8](http://imgur.com/K5FZAZ8)
I also tried to run from terminal emulator, and it closed immediately.

**Comment by giucam** [comment]
That's not a black screen, that's a missing wallpaper. Use [qt5ct](https://www.linux-apps.com/content/show.php/Qt5+Configuration+Tool?content=168066) and start orbital with QT_QPA_PLATFORMTHEME=qt5ct , and configure the wallpaper by clicking on the icon on the bottom right of the screen.

**Comment by Kais-DkM** [comment]
Oh, then why are the icons(for terminal and etc) are missing?
Are there any settings about that in qt5ct? I couldn't find it.

**Comment by giucam** [comment]
Yes, qt5ct has an "icon theme" tab. But of course you need an icon theme installed, such as oxygen.

**Comment by Kais-DkM** [comment]
Using qt5ct solved this problem! I still have other issues about unexpectable crashing, but at least icons and background is displaying.
I think I should edit title of this issue.

**Comment by giucam** [comment]
About the crash, can you open a new issue with a backtrace of the crash?

**Comment by Kais-DkM** [comment]
Of course. If I find reproductable situations, I'll open issues about that.
